### PR TITLE
Add tree-sitter-hcl support

### PR DESCRIPTION
**Pull request by mafrosis**
https://github.com/returntocorp/semgrep/issues/1147

### CODE REVIEW

**Comment by mjambon** [comment]
Hey @mafrosis , this is great! I believe the CI job fails because of some authentication token issue and 3rd-party pull requests. Don't worry about it, and let me know if you get stuck or ready to merge.

Locally, you should be able to do:
```
make && make install
cd lang
./test-lang hcl
cd hcl
make stat
```

It looks like you already put the necessary files in.

Then, the next step is to publish the generated code. This will go to a repo named [semgrep-hcl](https://github.com/returntocorp/semgrep-hcl) which I just created. This is done with

```
cd lang
./release hcl
```
The `git push` will fail because of permissions. At this point, I can do this for you. Or you can switch the remote in the local semgrep-hcl repo so as to push to your own fork of semgrep-hcl, and then make a pull request.

**Comment by mafrosis** [comment]
Thanks @mjambon 

I tried the `./release hcl` command, but seems there's a bug in there where it modifies a local file and then barfs because the git tree is modified:

```
> cd lang
> git status
On branch hcl
Your branch is up to date with 'origin/hcl'.

nothing to commit, working tree clean

> ./release hcl
git status is not clean.

Possible resolutions:
- pass the --dry-run option to release.
- add and commit files until 'git status' shows a clean status.

> git status
On branch hcl
Your branch is up to date with 'origin/hcl'.

Changes not staged for commit:
	modified:   semgrep-grammars/src/tree-sitter-hack (modified content)

no changes added to commit

> cd semgrep-grammars/src/tree-sitter-hack
> git status
HEAD detached at 9b4c90e
Changes not staged for commit:
	deleted:    bin/docker/build

no changes added to commit
```

**Comment by mjambon** [comment]
I don't know what's going on with this `bin/docker/build`. I think it's meant to be git-ignored, based on what was [done for tree-sitter-javascript](https://github.com/tree-sitter/tree-sitter-javascript/blob/master/.gitignore). You should update the .gitignore in tree-sitter-hcl. You can do it locally in your submodule, this should unblock you for the `release` job.

**Comment by mafrosis** [comment]
If it's indeed `.gitignore` then the problem is the trailing-slash here:
https://github.com/antoniodejesusochoasolano/tree-sitter-hack/blob/main/.gitignore#L2

I should have been more explicit before - the unstaged files are not in the `tree-sitter-hcl` code, but in the `tree-sitter-hcl` code

**Comment by mjambon** [comment]
Oops sorry, I didn't realize it's a problem with tree-sitter-hack, not tree-sitter-hcl.

The culprit must be this line:
```
lang/release:  find semgrep-grammars -name node_modules -or -name build | xargs rm -rf
```
It deletes `bin/docker/build` which is under git control. A fix might be in the command above to only delete folders named `build`.

**Comment by mafrosis** [comment]
Yes I just came to the same conclusion - I'll push another commit

**Comment by mafrosis** [comment]
https://github.com/returntocorp/semgrep-hcl/pull/1

**Pull request merged**
