### PR TITLE
Handling for symbols

### PR DESCRIPTION
**Pull request by ulziibay**
Lets handle A.STRING(name), A.PATTERN(name) as symbol

### CODE REVIEW

**Comment by ulziibay** [comment]
With this arithmetic grammar is normalized to:
```
("program",
 [("assignment_statement",
   (SIMPLE
      (SEQ
         [(SYMBOL "variable"); (SYMBOL "intermediate1");
           (SYMBOL "expression"); (SYMBOL "intermediate2")])));
   ("comment", (SIMPLE (ATOM (SYMBOL "#.*"))));
   ("expression",
    (CHOICE
       [(ATOM (SYMBOL "variable")); (ATOM (SYMBOL "number"));
         (ATOM (SYMBOL "intermediate4")); (ATOM (SYMBOL "intermediate5"));
         (ATOM (SYMBOL "intermediate6")); (ATOM (SYMBOL "intermediate7"));
         (ATOM (SYMBOL "intermediate8"))]));
   ("expression_statement",
    (SIMPLE (SEQ [(SYMBOL "expression"); (SYMBOL "intermediate3")])));
   ("intermediate1", (SIMPLE (ATOM (SYMBOL "="))));
   ("intermediate10", (SIMPLE (ATOM (SYMBOL "/"))));
   ("intermediate11", (SIMPLE (ATOM (SYMBOL "*"))));
   ("intermediate12", (SIMPLE (ATOM (SYMBOL "-"))));
   ("intermediate13", (SIMPLE (ATOM (SYMBOL "+"))));
   ("intermediate2", (SIMPLE (ATOM (SYMBOL ";"))));
   ("intermediate3", (SIMPLE (ATOM (SYMBOL ";"))));
   ("intermediate4",
    (SIMPLE
       (SEQ
          [(SYMBOL "expression"); (SYMBOL "intermediate13");
            (SYMBOL "expression")])));
   ("intermediate5",
    (SIMPLE
       (SEQ
          [(SYMBOL "expression"); (SYMBOL "intermediate12");
            (SYMBOL "expression")])));
   ("intermediate6",
    (SIMPLE
       (SEQ
          [(SYMBOL "expression"); (SYMBOL "intermediate11");
            (SYMBOL "expression")])));
   ("intermediate7",
    (SIMPLE
       (SEQ
          [(SYMBOL "expression"); (SYMBOL "intermediate10");
            (SYMBOL "expression")])));
   ("intermediate8",
    (SIMPLE
       (SEQ
          [(SYMBOL "expression"); (SYMBOL "intermediate9");
            (SYMBOL "expression")])));
   ("intermediate9", (SIMPLE (ATOM (SYMBOL "^"))));
   ("number", (SIMPLE (ATOM (SYMBOL "\\d+"))));
   ("program", (SIMPLE (ATOM TOKEN)));
   ("variable", (SIMPLE (ATOM (SYMBOL "\\a\\w*"))))])
```

**Comment by ulziibay** [comment]
Actually grammar for arithmetic is
```
("program",
 [("program",
   (REPEAT
      (CHOICE
         [(SYMBOL "assignment_statement"); (SYMBOL "expression_statement")])));
   ("assignment_statement",
    (SEQ
       [(SYMBOL "variable"); (STRING "="); (SYMBOL "expression");
         (STRING ";")]));
   ("expression_statement", (SEQ [(SYMBOL "expression"); (STRING ";")]));
   ("expression",
    (CHOICE
       [(SYMBOL "variable"); (SYMBOL "number");
         (SEQ [(SYMBOL "expression"); (STRING "+"); (SYMBOL "expression")]);
         (SEQ [(SYMBOL "expression"); (STRING "-"); (SYMBOL "expression")]);
         (SEQ [(SYMBOL "expression"); (STRING "*"); (SYMBOL "expression")]);
         (SEQ [(SYMBOL "expression"); (STRING "/"); (SYMBOL "expression")]);
         (SEQ [(SYMBOL "expression"); (STRING "^"); (SYMBOL "expression")])]));
   ("variable", (PATTERN "\\a\\w*")); ("number", (PATTERN "\\d+"));
   ("comment", (PATTERN "#.*"))])
```

**Comment by aryx** [comment]
This diffs seems wrong. I think it is a regression compared to the correctness-fix you had before.

**Comment by ulziibay** [comment]
A.STRING and A.PATTERN should map to B.SYMBOL. This diff achieves that

**Comment by ulziibay** [comment]
i will just merge the changes there

**Pull request merged**
