### PR TITLE
Move java to the modern setup

### PR DESCRIPTION
**Pull request by mjambon**
1. This now points to the latest commit of tree-sitter-java. Feel free to downgrade. I did not publish the generated code.
2. This adds the script `add-simple-lang` which takes care of setting a new tree-sitter language that has the usual structure (unlike typescript/tsx) and no funny dependencies (unlike yaml, I found out).

Closes https://github.com/returntocorp/ocaml-tree-sitter/issues/101

### CODE REVIEW

**Comment by aryx** [comment]
Ci failure?

**Comment by mjambon** [comment]
There are various glitches in the current setup. Still working on this.

**Comment by mjambon** [comment]
I fixed a few things and migrated the following languages to the modern setup:
* java
* go
* C
* C++

Additionally, this will now publish parsing stats for C and C++. For each language, the stats run on a single repo which we had already in there:
* C: 291548 lines, 99.535% success,
* C++: 387888 lines, 93.229% success 😬

**Review by aryx — COMMENTED** [review]
great work

**Comment by aryx** [comment]
it's not bad 93% for C++ given the use of insane cpp macros in most projects.
I'm curious how much it will be as we add more projects to stat on.

**Pull request merged**
