### PR TITLE
A few projects to test the tree-sitter C and C++ parser

### PR DESCRIPTION
**Pull request by aryx**
test plan:
make stat in the lang/c and lang/cpp directory.
I get 99.5% on git with the C parser and 93.1% on the Cataclysm
project with the C++ parser.

### CODE REVIEW

**Comment by aryx** [comment]
This will help https://github.com/returntocorp/semgrep/issues/1952

**Comment by aryx** [comment]
There are lots of errors on the git code, but the error-recovery of tree-sitter seems to work pretty well!

**Comment by aryx** [comment]
143 files failing (in lang/c/stat/stat.fail) but still 99.52% line coverage.
I wonder if we undercount errors ... 99.52% seems really high given the number of actual parse errors
there is in the parse-error.log file.

**Comment by mjambon** [comment]
If each error is contained in one line, 99.5% success corresponds to one error every 200 lines. So it's compatible with something like half of the files containing at least one error, which would be 50% success without error recovery.

**Review by mjambon — APPROVED** [review]

**Pull request merged**
